name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: make build
      run: mkdir builds && cd builds
    - name: cmake
      run: cmake ../ -G "Unix Makefiles"
    - name: cmake build
      run: cmake --build . -j 8
